//
//This program determines the
//average of a set of grades
//having the three grades
//randomly generated by
//the program
//
//Author: Jared Salvatore
//Date:   January 24, 2011
//

# include<ctime>
# include<iostream>

using namespace std;

int		randInt(int, int);

void	main(void){

	float		average;
	int		grade01;
	int		grade02;
	int		grade03;
	int		total;

	//
	//seeding random number generator
	//

srand(time(0));

	cout.setf(ios::fixed);
	cout.setf(ios::showpoint);
	cout.precision(2);

	grade01=randInt(50,100);
	cout << "Enter grade 01: "
		 << grade01
		 <<"\n";

	grade02=randInt(50,100);
	cout << "Enter grade 01: "
		 << grade02
		 <<"\n";

	grade03=randInt(50,100);
	cout << "Enter grade 01: "
		 << grade03
		 <<"\n";

	total = grade01 + grade02 + grade03;

	average = total / 3.0;

	cout<<"The average grade: ";
	cout<<average;

}//end main

//
// Function randInt
//

int randInt(int loBound, int hiBound) {

	int intervalSize;
	int randomOffset;
	int value;

	intervalSize = (hiBound - loBound) + 1;

	randomOffset = rand() % intervalSize;
	value = loBound + randomOffset;

	return value;

} // end randInt