//
//grades05.cpp
//
//This program determines the
//average of a set of grades
//having the three grades
//randomly generated by
//the program
//
//Author: Jared Salvatore
//Date:   January 24, 2011
//

# include<ctime>
# include<iostream>

using namespace std;

int		randInt(int, int);

void	main(void){

	float		average;
	int		classSize;
	int		count;
	bool	forever = true;
	int		grade;
	int		total;

	while(forever) {

	count = 0;
	cout << "Enter a Class Size: ";
	cin >> classSize;
		while(count < classSize){
		cout << "Enter a Grade: ";
		cin >> grade;
		total = total + grade;
		count = count + 1;
		}//endwhile
	average = total / classSize;
	cout << "Class Average Grade is: ";
	     << average;
	     << "\n";

	}endwhile

}endmain

